apiVersion: v1
kind: Service
metadata:
  name: helloworldwebapp-service
  namespace: helloworld
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: helloworldwebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80